DROP TABLE IF EXISTS public.orders_discounts;
CREATE TABLE public.orders_discounts (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	order_id uuid NOT NULL,
	discount_id uuid NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT orders_discounts_pkey PRIMARY KEY (id)
);

DROP SEQUENCE IF EXISTS public.orders_discounts_id_seq;
CREATE SEQUENCE public.orders_discounts_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
