DROP TABLE IF EXISTS public.product_brands;

CREATE TABLE
    public.product_brands (
        id int8 NOT NULL GENERATED ALWAYS AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        "name" text NOT NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_brands_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_groups;

CREATE TABLE
    public.product_groups (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        "name" text NOT NULL,
        attribute_ids _int8 NOT NULL DEFAULT '{}':: bigint [],
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_groups_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.tags;

CREATE TABLE
    public.tags (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        "name" varchar NOT NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT tags_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_categories;

CREATE TABLE
    public.product_categories (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        "name" text NOT NULL UNIQUE,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_subcategories;

CREATE TABLE product_subcategories (
    id int8 NOT NULL GENERATED ALWAYS AS IDENTITY(
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
    ),
    "name" text NOT NULL,
    product_category_id int8 NOT NULL,
    -------------------------------------
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz NULL,
    -------------------------------------
    CONSTRAINT product_subcategories_pkey PRIMARY KEY (id),
    CONSTRAINT product_subcategories_unique UNIQUE (product_category_id, "name")
);

-------------------------------------------------------------

DROP TABLE IF EXISTS public.spec_fields;

CREATE TABLE
    public.spec_fields (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        "name" text NOT NULL UNIQUE,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT spec_fields_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_attributes;

CREATE TABLE
    public.products_attributes (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        product_id uuid NOT NULL,
        attribute_id int8 NOT NULL,
        value text NOT NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_attributes_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_reviews;

CREATE TABLE
    public.product_reviews (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        message text NOT NULL DEFAULT '':: text,
        rating int2 NOT NULL,
        customer_id uuid NOT NULL,
        product_id uuid NOT NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
        CONSTRAINT product_reviews_
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.product_tags;

CREATE TABLE
    public.product_tags (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        product_id uuid NOT NULL,
        tag_id int8 NOT NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT product_tags_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.products;

CREATE TABLE
    public.products (
        id uuid NOT NULL DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        briefDescription text NULL DEFAULT '':: text,
        description text NULL DEFAULT '':: text,
        thumbnail text NULL,
        price numeric NULL DEFAULT 0.00,
        brand_id int8 NULL,
        category_id int8 NULL,
        product_group_id int8 NULL,
        categories _text NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT products_name_key UNIQUE (name),
        CONSTRAINT products_pkey PRIMARY KEY (id)
    );

-------------------------------------------------------------

DROP TABLE IF EXISTS public.products_specs;

CREATE TABLE
    public.products_specs (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ),
        product_id uuid NOT NULL,
        spec_field_id int8 NOT NULL,
        value text NULL,
        -------------------------------------
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        deleted_at timestamptz NULL,
        -------------------------------------
        CONSTRAINT products_specs_pkey PRIMARY KEY (id)
    );
